#+TITLE: UD07 - Repaso - Discos Duros
#+AUTHOR: Angel Berlanas
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black}

* Aviso navegantes

  Leed atentamente los enunciados. Vale la pena leer el ejercicio hasta el final
  antes de pasar a la práctica.

* Discos duros - Conectores

  Enumera los conectores disponibles para los discos duros siguientes, indicando
  el ancho de banda, así como el número de conectores en la placa que solemos
  tener (en placas entre 75 y 100 euros) para cada uno de ellos.

  | Conector |
  |----------|
  | IDE      |
  | SATA 1   |
  | SATA 2   |
  | SATA 3   |
  | M.2      |

  Para cada uno de ellos indicad de /donde/ habéis extraido la información
  acerca del ancho de banda.

* Discos duros - fsck

  Busca en internet información acerca de ~fsck~. Responde a las siguientes
  preguntas.

  - ¿Qué funcion realiza?.
  - ¿Porqué hay que ejecutarlo a veces después de un reinicio /inesperado/?.
  - Trata de ejecutarlo en una Máquina MV sobre la partición de ~/~.¿Qué ocurre?.
  - ¿Cómo lo harías para realizarlo?

* Discos duros - chkdsk

  Busca en internet información acerca de ~chkdsk~. Responde a las siguientes
  preguntas:

  - ¿Qué funcion realiza?.
  - ¿Porqué hay que ejecutarlo a veces después de un reinicio /inesperado/?.
  - ¿Se puede forzar la ejecución en un reinicio? 
    
  


