#+TITLE: UD07 - Hablando con el Sistema
#+AUTHOR: Angel Berlanas
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black}

* Descripción

En la empresa /Soluciones Eficientes de Alta Disponibilidad/, nos han pedido el
mantenimiento de una serie de equipos a los que hemos instalado un Sistema
GNU/Linux para posteriormente (/semana que viene/) configurar un RAID.

Previo a la instalación vamos a elaborar una serie de comandos que nos van a
servir para mas tarde poder realizar el /mantenimiento/ de dichos sistemas. 

* Registros del Sistema

Escribe los comandos necesarios para realizar las siguientes acciones:

** Ejercicio 01

   ¿Qué comando nos permitirá saber cuando ha sido la última vez que arrancó la
   máquina?

** Ejercicio 02
   
   Obtén tu IP y velocidad del enlace en la red LOCAL.

** Ejercicio 03

   Sistema Operativo Instalado

** Ejercicio 04
   
   Número de particiones de un disco duro dado (/dev/sda)

** Ejercicio 05
   
   Tamaño de la partición montada en ~/~.

** Ejercicio 06 

   Carpeta de ~/~ que ocupa /más/ espacio.

** Ejercicio 07

   Carpeta de ~/~ que ocupa /menos/ espacio.

** Ejercicio 08

   La 2ª Carpeta de ~/usr/share~ que ocupa /más/ espacio.

** Ejercicio 09 

   La antepenúltima carpeta que ocupa /menos/ espacio en ~/usr/lib~.

** Ejercicio 10

   Cuantas veces ha sido conectado un USB en el equipo desde que arrancó.

** Ejercicio 11

   Cuál es el volumen de sonido del altavoz principal.

** Ejercicio 12

   Cuantas pantallas hay conectadas y a qué resolución.

* Entrega 

  En un /PDF/ copia el enunciado y cada uno de los comandos que se deben
  ejecutar para resolver el /problema/.



