#+TITLE: UD08 - Tarjetas
#+AUTHOR: Angel Berlanas
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black}

* Introducción

  Conceptos sobre la ampliación y modificación.
  El modelo de PC y Amstrad.
  Conexiones en el modelo de Von Neumman.

* Conexiones a la placa base

  Historia de las conexiones
  AGP
  PCI Express
  
* PCIExpress

  PCI Express está organizado en lanes. Cada lane tiene un conjunto
  independiente de pines de transmisión y recepción, y los datos pueden enviarse
  en ambas direcciones simultáneamente. Y aquí es donde las cosas se vuelven
  engañosas. El ancho de banda en una sola dirección para un solo lane PCIe 1.0
  (x1) es de 250 MB/s, pero debido a que puede enviar y recibir 250 MB/s al
  mismo tiempo a Intel le gusta indicar el ancho de banda disponible para una
  ranura PCIe 1.0 x1 como 500 MB / s . Si bien ese es el ancho de banda total
  agregado disponible para una sola ranura, solo puedes alcanzar esa cifra de
  ancho de banda si estás leyendo y escribiendo al mismo tiempo.


   * Las conexiones ‘PCIe x1’ tienen un lane de datos
   * Las conexiones ‘PCIe x4’ tienen cuatro lanes de datos
   * Las conexiones ‘PCIe x8’ tienen ocho lanes de datos
   * Las conexiones ‘PCIe x16’ tienen dieciséis lanes de datos
   * Las conexiones ‘PCIe x32’ tienen treinta y dos lanes de datos (actualmente, son muy raras)
     
 | Velocidad  | 	PCI-e 1.0 | 	PCI-e 2.x	 | PCI-e 3.0       | 	PCI-e 4.x |
 |------------+-------------------+---------------------------+-----------------+-------------------|
 | x1	 | 250MB/s	   | 500MB/s	           | 985MB/s	 | 1969MB/s          |
 | x4         | 1000MB/s          | 2000MB/s                  | 3940MB/s        | 7876MBs           |
 | x8         | 2000MB/s          | 4000MB/s                  | 7880MB/s        | 15752MB/s         |
 | x16        | 4000MB/s          | 8000MB/s                  | 15760MB/s       | 31504MB/s         |


* Tipos de Tarjeta



