#+TITLE: UD10 - Periféricos - Impresoras
#+AUTHOR: Angel Berlanas Vicente
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black}

* Tarea : cups-PDF

  Instalar en la máquina virtual el paquete ~cups-pdf~ y configurar la impresora
  para que su /Directorio de Salida/ sea :

  ~/srv/impresoras/~

  Comprobar que la ruta está creada, tiene los permisos, etc...

  Adjuntar captura de que se está imprimiendo allí además de:

  * El registro del servicio de impresión. 
  * El fichero de configuración modificado.
  * Una captura donde se muestren los permisos y la ruta del fichero.
  

* Tarea : Tenkeyless 01
  
  Busca en Internet información acerca de estos teclados. ¿Qué tipo de usuari@s los
  suele adquirir / configurar.?

* Tarea : Tenkeyless  02

  Buscando en Internet acerca de los teclados Tenkeyless hemos encontrado esta
  descripción:

  | Component      | -             |
  | Switches       | Cherry MX     |
  | Lighting       | White per-key |
  | Programmable   | Yes           |
  | Keycap Profile | OEM           |
  | Stabilizers    | Cherry Style  |

  Explica con tus palabras que significa cada uno de estos componentes y
  prestaciones.


