#+TITLE: UD10 - Periféricos - Teclados
#+AUTHOR: Angel Berlanas
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black}

* Tarea : Teclados ergonómicos.

  Busca en Internet 3 teclados ergónomicos de diferente disposición. Debes poder
  adquirilos, es decir debes buscarlos en Webs donde pudieras comprarlos.

  Adjunta el enlace, el precio y una pequeña descripción de /porqué/ ese teclado
  es mejor para las articulaciones.

* Tarea : Tenkeyless 01
  
  Busca en Internet información acerca de estos teclados. ¿Qué tipo de usuari@s los
  suele adquirir / configurar.?

* Tarea : Tenkeyless  02

  Buscando en Internet acerca de los teclados Tenkeyless hemos encontrado esta
  descripción:

  | Component      | -             |
  | Switches       | Cherry MX     |
  | Lighting       | White per-key |
  | Programmable   | Yes           |
  | Keycap Profile | OEM           |
  | Stabilizers    | Cherry Style  |

  Explica con tus palabras que significa cada uno de estos componentes y
  prestaciones.


