#+TITLE: UD 08 - Tarea - Lanes PCI
#+AUTHOR: Angel Berlanas
#+EMAIL: berlanas_ang@gva.es
#+LANGUAGE: es
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black}

* Presentación de la actividad

  Con lo explicado en clase + el vídeo que se indica en la tarea, responder a
  las preguntas que se plantean en la tarea.

  [[https://www.youtube.com/watch?v=J4eSCMtaRuQ][{ YouTube } - Líneas PCI]]

* Ejercicio 01

  ¿Cuantos /buses pci express/ hay en el diagrama?

* Ejercicio 02

  ¿Donde se realiza el /switching/ de las líneas PCI express?

* Ejercicio 03

  ¿Los puertos PCI express y las líneas deben ser las mismas?¿Porqué?

* Ejercicio 04

  ¿Cuantas líneas dedicadas al Chipset es lo /habitual/?

* Ejercicio 05

  ¿Podríamos pasar de 16 lanes a 10 para el conector ~x16~?¿Porqué?

* Ejercicio 06 

  ¿De que dos maneras se pueden comunicar con la CPU un Disco Duro ~m.2~?

* Ejercicio 07

  En el vídeo aparecen los conceptos /protocolo PCI express y SATA/, ¿Qué
  diferencias hay en el uso de uno u otro por parte del dispositivo que lo
  utiliza?

* Ejercicio 08

  ¿Qué significan las siglas /PCH/ en el vídeo?¿De qué se encarga este
  dispositivo?


* Ejercicio 09

  ¿Sobre que voltaje trabaja ~PCI-e~?

* Ejercicio 10

  Traduce el texto siguiente:

  On June 18, 2019, PCI-SIG announced the development of PCI Express 6.0
  specification. Bandwidth is expected to increase to 64 GT/s, yielding 128 GB/s
  in each direction in a 16-lane configuration, with a target release date of
  2021.The new standard uses 4-level pulse-amplitude modulation (PAM-4)
  with a low-latency forward error correction (FEC) in place of
  non-return-to-zero (NRZ) modulation.Unlike previous PCI Express versions,
  forward error correction is used to increase data integrity and PAM-4 is used
  as line code so that two bits are transferred per transfer. With 64 GT/s data
  transfer rate (raw bit rate) and up to 256 GB/s via x16 configuration .
  

* Ejercicio 11

  ¿Qué signficia ~NRZ~?¿Qué es una modulación?

* Ejercicio 12

  Si tenemos una configuración ~x16~ de /PCIexpress/ en nuestro ordenador,
  dependiendo de la versión de PCIe que usemos podremos obtener diferentes
  anchos de banda. Elabora una tabla con:

  | Version | Voltaje | Potencia | Ancho de Banda |
  |---------+---------+----------+----------------|
  | x16     | -       | -        | -              |
  

  Cada fila ha de ser rellenadas con los datos referentes a una versión de /PCIe/.

