#+TITLE: UD09 - Repaso - Placas Base
#+AUTHOR: Angel Berlanas Vicente
#+EMAIL: berlanas_ang@gva.es
#+LANGUAGE: es
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black}

* Aviso navegantes

  Leed atentamente los enunciados de las actividades y buscad soluciones que se
  adapten a las necesidades.

* Pregunta 01 : Placas Base.

  La placa base es uno de los componentes más importantes de nuestro ordenador,
  sin embargo se le presta poca atención más allá de que sea capaz de soportar
  los diferentes componentes que van /sobre/ ella. Esto a veces da lugar a un
  fenómeno muy habitual en el mundo de los computadores que es el /Cuello de
  Botella/. Redacta un pequeño texto en el que expliques de manera sencilla en
  que consiste dicho problema y sobre que tipo de recursos se suele dar.

* Pregunta 02 : SouthBridge
  
  En el puente sur /(SouthBridge)/ están una conectados una serie de
  dispositivos. ¿Qué tipos de dispositivos son?. 

* Pregunta 03 : dmidecode

  Si hechábais en falta los scripts...no hay problema aquí tenéis unos pocos
  para que no perdamos la costumbre.

  Para obtener la nota máxima por cada uno de los scripts deben ser ejecutados y
  que devuelvan exáctamente lo mismo que se muestra (tened en cuenta que puede
  ser diferente en vuestras máquinas, pero no vale hacer un ~echo COSAS~).

  Probad los scripts, aseguraos que muestran /exactamente lo que pido/. Es muy
  sencillo obtener un 10 y muy facil un 0.

  Pistas: /Todos los scripts se realizan parseando la salida de ~dmidecode~ y/
  /ejecutando operaciones sobre esos datos obtenidos./.

  Para la ejecución de esto necesitaréis o un **GNU/LinuX** instalado o la
  Máquina Virtual.

  Los nombres de los scripts son los que aparecen como título de los diferentes apartados.

** dmidecode01.sh

   Debe mostrar el voltaje al que trabaja vuestro procesador:

   |**Ejecución** : | ~sudo ./dmidecode01.sh~  |
   |**Salida**: | ~Voltios: 1.3 V~.  |

** dmidecode02.sh

   Debe mostrar el /Vendor/ de la BIOS.

   |**Ejecución** : | ~sudo ./dmidecode02.sh~  |
   |**Salida**: | ~Vendedor: American Megatrends Inc~.|

** dmidecode03.sh

   Debe indicar si soporta UEFI.

   | **Ejecución** : | ~sudo ./dmidecode03.sh~ |
   | **Salida**:     | ~Soporta UEFI : Si~.     |

** dmidecode04.sh

   Debe indicar de cada uno de los Slots de PCIExpress x1 que voltaje provee y
   si está disponible o no.

   | **Ejecución** : | ~sudo ./dmidecode04.sh~       |
   | **Salida**:     | ~x1_1 : Disponible : 3,3 V~. |
   |                 | ~x1_2 : No disponible: 3,3 V~. |
   
   
* Pregunta 04 : BIOS y UEFI.

  ¿Recordáis el texto en inglés que hablaba del arranque de un equipo?
  Indica en el proceso que vas a ver a continuación si hubiera algún error:

  | Paso | Descripción                                                                       |
  |    1 | Equipo se pone en marcha.                                                         |
  |    2 | La BIOS comprueba que disco duro es el primero.                                   |
  |    3 | Se ejecuta el POST.                                                               |
  |    4 | Una vez seleccionado el disco duro, se busca el sector de arranque.               |
  |    5 | En el caso de las UEFIs se permiten tamaños más grandes de particiones            |
  |    6 | No se puede modificar el siguiente reinicio desde el Sistema Operativo arrancado. |
  
  En caso de que hubiera algún error puede estar en dos sitios: Por un lado en
  el /orden/ de la ejecución y por otro en la /Descripción/. Reescribe los pasos
  indicando qué matiz debe corregirse para que sea cierto. Tenéis la solución en
  el artículo ^_^.
   
   
