#+TITLE: UD08 - Repaso - Tarjetas Ethernet
#+AUTHOR: Angel Berlanas Vicente
#+EMAIL: berlanas_ang@gva.es
#+LANGUAGE: es
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black}

* Aviso navegantes

  Leed atentamente los enunciados de las actividades y buscad soluciones que se
  adapten a las necesidades.

  No busquéis en Internet las soluciones, pensar una vosotr@s y a partir de esa
  solución, buscad los trozos necesarios para que funcione.

* Pregunta 01 : Drivers

  ¿Qué es un driver? ¿Qué es un módulo del kernel?

* Pregunta 02 : Drivers y Virtualbox

  Con una máquina virtual que tengáis instalada con un sistema basado en Ubuntu,
  realizar los siguientes pasos:

  - Establecer que red está en "Adaptador Puente".
  - Iniciar la MV.
  - Comprobar la ip de la tarjeta de red.
  - Instalar el ~openssh-server~ en la MV (/Guest/).
  - Intentar conectaros a la máquina (/Guest/) mediante ssh : ~ssh
    usuario@maquinaVM~
  - Adjuntar captura de haberlo conseguido.
  
  Documenta todo el proceso.

  Realiza la misma conexión pero estableciendo la red en el VirtualBox en los
  siguientes modos (recuerda que debes reiniciar tras cada cambio):

  | Modo           | IP de MV | Resultado (SI/NO) |
  |----------------+----------+-------------------|
  | Solo anfitrion |          |                   |
  | Nat            |          |                   |
  | Red NAT        |          |                   |
  
* Pregunta 03 : NAT y Red NAT 

  ¿Qué diferencia hay entre NAT y Red NAT?¿Podemos conectarnos desde el /Guest/
  al /Host/?. ¿Podemos hacer ping? 

* Pregunta 04 : Ethernet

  Todas las tarjetas de red son similares, sin embargo debemos diferenciar entre
  las alámbricas y las inalámbricas. El estándar de ethernet es el ~802.3~ del
  IEEE.

  ¿Cuáles son las velocidades actuales de las tarjetas de red respecto a la
  conexión ethernet?. 

* Pregunta 05 : Wifi

  Las tarjetas Wifi son muy habituales hoy en dia. El estándar de WiFi es el
  ~802.11~, que podéis encontrar en internet fácilmente.

  La configuración de las WiFis requiere de una seríe de parámetros habituales:

  Elabora un pequeño texto (no más de 200 palabras) donde expliques cuáles son
  los pasos necesarios para /conectarte/ a una red Wifi.

* Pregunta 06 : Canales Wifi
  
  De la Wikipedia:

  Los estándares 802.11b y 802.11g utilizan la banda de 2,4 GHz. En esta banda
  se definieron 11 canales utilizables por equipos wifi, que pueden configurarse
  de acuerdo a necesidades particulares. Sin embargo, los 11 canales no son
  completamente independientes (un canal se superpone y produce interferencias
  hasta un canal a 4 canales de distancia). El ancho de banda de la señal (22
  MHz) es superior a la separación entre canales consecutivos (5 MHz), por eso
  se hace necesaria una separación de al menos 5 canales con el fin de evitar
  interferencias entre celdas adyacentes, ya que al utilizar canales con una
  separación de 5 canales entre ellos (y a la vez cada uno de estos con una
  separación de 5 MHz de su canal vecino) entonces se logra una separación final
  de 25 MHz, lo cual es mayor al ancho de banda que utiliza cada canal del
  estándar 802.11, el cual es de 22 MHz. Tradicionalmente se utilizan los
  canales 1, 6 y 11, aunque se ha documentado que el uso de los canales 1, 5, 9
  y 13 (en dominios europeos) no es perjudicial para el rendimiento de la red.

  Describe /con tus palabras/ qué nos dice este texto.

  Utilizando las herramientas necesarias  ([[https://bestforandroid.com/wifi-signal-apps/][este enlace es un buen punto de
  partida]]), comprueba la conectividad de tu casa.

  ¿Qué canales se están usando?

* Pregunta 07 : Comandos de red Windows

  Elabora un pequeño listado de comandos de Windows que nos permitan conocer el
  estado de la red:

  | Función                            | Comando |
  |------------------------------------+---------|
  | Saber la IP                        |         |
  | Cambiar la IP                      |         |
  | Forzar la petición DHCP            |         |
  | Resolver una dirección de Internet |         |
  | Reiniciar la red                   |         |
  | Vaciar la caché de DNS             |         |
  | Obtener la puerta de enlace        |         |
  
* Pregunta 08 : Comandos de red (GNU/LinuX)
  
  Elabora un pequeño listado de comandos de GNU/LinuX que nos permitan conocer el
  estado de la red:

  | Función                            | Comando |
  |------------------------------------+---------|
  | Saber la IP                        |         |
  | Cambiar la IP                      |         |
  | Forzar la petición DHCP            |         |
  | Resolver una dirección de Internet |         |
  | Reiniciar la red                   |         |
  | Vaciar la caché de DNS             |         |
  | Obtener la puerta de enlace        |         |
                                       

